### ISSUE TITLE
better platform specific code

### ISSUE THREAD

**Issue by kellams** [alexanderremm/RGE#1]
I feel like the window class should not be split into different files depending on OS but something like this should used to separate the platform specific code.

```
if (WIN32)
    #do something
endif (WIN32)

if (UNIX)
    #do something
endif (UNIX)
```
https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Write-Platform-Checks

**Comment by alexanderremm** [comment]
Yeah, what I have right now is really hacky. I think making one file for the window implementation is ideal.

**Comment by kellams** [comment]
Thank you for the quick response! A config file may be a good idea but not sure how that would be implemented. 👽

**Comment by alexanderremm** [comment]
Might want to take a look at [this](http://wiki.c2.com/?PimplIdiom)

**Comment by kellams** [comment]
Thank you for resolving (or rather closing) this issue!
